// Fetch Users Data
export const FETCH_USERS_DATA_REQUEST = "FETCH_USERS_DATA_REQUEST";
export const FETCH_USERS_DATA_SUCCESS = "FETCH_USERS_DATA_SUCCESS";
export const FETCH_USERS_DATA_FAILURE = "FETCH_USERS_DATA_FAILURE";

export const FETCH_MORE_USERS_DATA_REQUEST = "FETCH_MORE_USERS_DATA_REQUEST";
export const FETCH_MORE_USERS_DATA_SUCCESS = "FETCH_MORE_USERS_DATA_SUCCESS";
export const FETCH_MORE_USERS_DATA_FAILURE = "FETCH_MORE_USERS_DATA_FAILURE";

// Fetch Repositories Data
export const FETCH_REPOSITORIES_DATA_REQUEST = "FETCH_REPOSITORIES_DATA_REQUEST";
export const FETCH_REPOSITORIES_DATA_SUCCESS = "FETCH_REPOSITORIES_DATA_SUCCESS";
export const FETCH_REPOSITORIES_DATA_FAILURE = "FETCH_REPOSITORIES_DATA_FAILURE";

export const FETCH_MORE_REPOSITORIES_DATA_REQUEST = "FETCH_MORE_REPOSITORIES_DATA_REQUEST";
export const FETCH_MORE_REPOSITORIES_DATA_SUCCESS = "FETCH_MORE_REPOSITORIES_DATA_SUCCESS";
export const FETCH_MORE_REPOSITORIES_DATA_FAILURE = "FETCH_MORE_REPOSITORIES_DATA_FAILURE";
